# Generated by Django 4.2.4 on 2023-09-06 00:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_allergy"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Allergy",
        ),
    ]
