name: Django CI

env:
  DB_NAME: github_actions
  DB_USER: postgres
  DB_PASSWORD: postgres
  DB_HOST: 127.0.0.1
  DB_PORT: 5432

  OPENAI_SECRET_API_KEY: ${{ secrets.OPENAI_SECRET_API_KEY }}
  DJANGO_SECRET_KEY: ${{ secrets.DJANGO_SECRET_KEY }}

  DJANGO_DEBUG: True

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:  
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.9]

    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: github_actions
        ports:
          - 5432:5432
        # need because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r backend/requirements.txt
    - name: Run migrations
      run: |
        python backend/manage.py migrate
    # TODOEDIT
    - name: Load fixtures
      run: python backend/manage.py loaddata backend/core/fixtures/*.json
    - name: Run Tests
      run: |
        python backend/manage.py test backend/ --exclude-tag=slow
